env:
  global:
    - CONAN_USERNAME: "sechinm"
    - CONAN_REFERENCE: "googlecloudcpp/0.1"
    - CONAN_REMOTE: "sechinm"
    - CONAN_CHANNEL: "testing"

linux: &linux
  os: linux
  sudo: required
  language: python
  python: "3.6"
  services:
    - docker

matrix:
  include:
    - <<: *linux
      env: CONAN_GCC_VERSIONS=6 CONAN_DOCKER_IMAGE=lasote/conangcc6

    - <<: *linux
      env: CONAN_GCC_VERSIONS=7 CONAN_DOCKER_IMAGE=lasote/conangcc7

    - <<: *linux
      env: CONAN_GCC_VERSIONS=8 CONAN_DOCKER_IMAGE=lasote/conangcc8


install:
  - pip install conan --upgrade
  - pip install conan_package_tools
  - conan user

script:
  python build.py